Реализовать форму для генерации шаблона #7
ilb/cloudtreasury pull request #8
Opened 2022-08-24 14:51 UTC by tyort

2022-08-26 06:29 UTC, MaximumQuiet requested changes

2022-08-26 06:29 UTC, MaximumQuiet commented on pages/fairprice/calculate.js
> +        {header()}
Тут можно не вызывать функцию, а использовать сразу компонент Header

2022-08-26 06:29 UTC, MaximumQuiet commented on pages/fairprice/header/header.js
> +import Link from 'next/link';
Header - это не страница, а компонент, поэтому его нужно разместить в папке components/Header.jsx
Ну и названия компонентов должны быть с большой буквы const Header = ({}) =>

2022-09-06 07:54 UTC, lianlun1 reviewed
При генерации отчета с датой по умолчанию отчет не скачивается.
![image](https://user-images.githubusercontent.com/93830765/188578272-59074202-47eb-4033-b7d0-8d7861eae036.png)
Если выбрать любую другую дату остается ошибка ```должно иметь обязательное поле date```

2022-09-06 11:25 UTC, MaximumQuiet approved these changes

2022-09-06 11:25 UTC, merged